---

- name: Check OS version and family
  when:
      - os_check
  ansible.builtin.assert:
      that: (ansible_facts.distribution == 'Amazon' and ansible_facts.distribution_major_version is version_compare('2', '=='))
      fail_msg: "This role can only be run against Supported OSs. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
      success_msg: "This role is running against a supported OS {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }}"
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(min_ansible_version, '>=')
      fail_msg: "You must use Ansible {{ min_ansible_version }} or greater"
      success_msg: "This role is running a supported version of ansible {{ ansible_version.full }} >= {{ min_ansible_version }}"
  tags:
      - always

- name: "check sugroup exists if used"
  block:
      - name: "Check su group exists if defined"
        ansible.builtin.command: grep -w "{{ amazon2cis_sugroup }}" /etc/group
        changed_when: false
        failed_when: sugroup_exists.rc >= 2
        register: sugroup_exists
        tags:
            - skip_ansible_lint

      - name: Check sugroup if defined exists before continuing
        ansible.builtin.assert:
            that: sugroup_exists.rc == 0
            msg: "The variable amazon2cis_sugroup is defined but does not exist please rectify"
  when:
      - amazon2cis_sugroup is defined
      - amazon2cis_rule_5_7
  tags:
      - rule_5.7

- name: Run pre-reqs
  ansible.builtin.import_tasks:
      file: check_prereqs.yml
  tags:
      - always
      - prereqs

- name: Run prelim tasks
  ansible.builtin.import_tasks:
      file: prelim.yml
  tags:
      - prelim_tasks
      - always

- name: Run pre-remediation audit
  ansible.builtin.import_tasks:
      file: pre_remediation_audit.yml
  when:
      - run_audit
  tags:
      - run_audit

- name: Gather the package facts
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - always

- name: Import section 1 tasks
  ansible.builtin.import_tasks:
      file: section_1/main.yml
  when: amazon2cis_section1
  tags:
      - amazon2cis_section1

- name: Import section 2 tasks
  ansible.builtin.import_tasks:
      file: section_2/main.yml
  when: amazon2cis_section2
  tags:
      - amazon2cis_section2

- name: Import section 3 tasks
  ansible.builtin.import_tasks:
      file: section_3/main.yml
  when: amazon2cis_section3
  tags:
      - amazon2cis_section3

- name: Import section 4 tasks
  ansible.builtin.import_tasks:
      file: section_4/main.yml
  when: amazon2cis_section4
  tags:
      - amazon2cis_section4

- name: Import section 5 tasks
  ansible.builtin.import_tasks:
      file: section_5/main.yml
  when: amazon2cis_section5
  tags:
      - amazon2cis_section5

- name: Import section 6 tasks
  ansible.builtin.import_tasks:
      file: section_6/main.yml
  when: amazon2cis_section6
  tags:
      - amazon2cis_section6

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: POST | reboot system if changes require it and not skipped
  block:
      - name: POST | Reboot system if changes require it and not skipped
        ansible.builtin.reboot:
        when:
            - change_requires_reboot
            - not skip_reboot

      - name: POST | Warning a reboot required but skip option set
        ansible.builtin.debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
        changed_when: true
        when:
            - change_requires_reboot
            - skip_reboot

      - name: "POST | Warning a reboot required but skip option set | warning count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        when:
            - change_requires_reboot
            - skip_reboot
  vars:
      warn_control_id: Reboot_required

- name: run post_remediation audit
  ansible.builtin.import_tasks:
      file: post_remediation_audit.yml
  when:
      - run_audit
  tags:
      - run_audit

- name: Show Audit Summary
  ansible.builtin.debug:
      msg: "{{ audit_results.split('\n') }}"
  when:
      - run_audit
  tags:
      - run_audit
