---

- name: systemd restart tmp.mount
  ansible.builtin.systemd:
      name: tmp.mount
      daemon_reload: true
      enabled: true
      masked: false
      state: reloaded

- name: Remount dev_shm
  ansible.posix.mount:
      name: /dev/shm
      state: remounted

- name: Remount home
  ansible.posix.mount:
      name: /home
      state: remounted

- name: Remount var
  ansible.posix.mount:
      name: /var
      state: remounted

- name: Remount var_tmp
  ansible.posix.mount:
      name: /var/tmp
      state: remounted

- name: Remount var_log
  ansible.posix.mount:
      name: /var/log
      state: remounted

- name: Remount var_log_audit
  ansible.posix.mount:
      name: /var/log/audit
      state: remounted

- name: systemd daemon reload
  ansible.builtin.systemd:
      daemon_reload: true

- name: Rebuild_grub
  ansible.builtin.command: /sbin/grub2-mkconfig -o "{{ amazon2cis_bootloader_file }}"

- name: Restart_postfix
  ansible.builtin.service:
      name: postfix
      state: restarted

- name: Sysctl_flush_ipv4_routes
  ansible.posix.sysctl:
      name: net.ipv4.route.flush
      value: '1'
      sysctl_set: true
  ignore_errors: true  # noqa ignore-errors
  when:
      - not system_is_container

- name: Sysctl_flush_ipv6_routes
  ansible.posix.sysctl:
      name: net.ipv6.route.flush
      value: '1'
      sysctl_set: true
  ignore_errors: true  # noqa ignore-errors
  when:
      - not system_is_container

- name: Restart_rsyslog
  ansible.builtin.service:
      name: rsyslog
      state: restarted

- name: Restart_journald
  ansible.builtin.service:
      name: systemd-journald
      state: restarted

- name: Restart_systemd_journal_upload
  ansible.builtin.service:
      name: systemd-journal-upload
      state: restarted

- name: update auditd
  ansible.builtin.template:
      src: audit/99_auditd.rules.j2
      dest: /etc/audit/rules.d/99_auditd.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd

- name: restart auditd
  ansible.builtin.command: /sbin/service auditd restart
  check_mode: false
  failed_when: false
  when:
      - not amazon2cis_skip_for_travis
  tags:
      - skip_ansible_lint

- name: grub2cfg
  ansible.builtin.command: /sbin/grub2-mkconfig -o "{{ amazon2cis_bootloader_file }}"
  notify: Change_requires_reboot

- name: restart rsyslog
  ansible.builtin.service:
      name: rsyslog
      state: restarted

- name: restart sshd
  ansible.builtin.service:
      name: sshd
      state: restarted

- name: Change_requires_reboot
  ansible.builtin.set_fact:
      change_requires_reboot: true
